spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: P#1zxcvbnm,./
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_indentifiers: ture
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false
    
 
    
    